function [] = WriteNC_2D(namefile, time, depth, data, varname, unit, long_varname)

if time(1)<3000
    % then it is decimal year
    time = datenum(time,1,1) - datenum(1900,1,1,0,0,0);
elseif time(1)>401767
    % then it is in Matlab format
    time = time - datenum(1900,1,1,0,0,0);
else
    % then it is already in the good format
    warning('Time vector already in days since 1900-1-1 0:0:0')
end

     WriteNetCDF2(namefile,time, ...
         'VariableName','time', ...
         'DimensionNames',{'time'},...
         'Unit', 'days since 1900-1-1 0:0:0', ...
         'LongVariableName','Time (UTC)');

     if or(size(depth) ==1,size(depth,2) ==1)
%          if there is one depth scale for all the columns then we use it
%          as dimension
         WriteNetCDF2(namefile,depth, ...
             'VariableName','depth', ...
             'DimensionNames',{'depth'},...
             'Unit', 'm', ...
             'LongVariableName','Depth');
         
         for i=1:length(data)
                 WriteNetCDF2(namefile,data{i}, ...
                     'VariableName',varname{i}, ...
                     'DimensionNames',{'depth','time'},...
                     'Unit', unit{i}, ...
                     'LongVariableName',long_varname{i});
         end
     else
        % Otherwise we use "level" as dimension and add depth as a variable
        level = 1:size(depth,1);
        WriteNetCDF2(namefile,level', ...
            'VariableName','level', ...
            'DimensionNames',{'level'},...
            'Unit', '', ...
            'LongVariableName','Model level');
         
        for i=1:length(data)
             WriteNetCDF2(namefile,data{i}, ...
                 'VariableName',varname{i}, ...
                 'DimensionNames',{'level','time'},...
                 'Unit', unit{i}, ...
                 'LongVariableName',long_varname{i});
        end

        WriteNetCDF2(namefile,depth, ...
            'VariableName','depth', ...
            'DimensionNames',{'level','time'},...
            'Unit', 'm', ...
            'LongVariableName','Depth bellow the surface');
     end
end